version: "3.8"

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "GersemiDb"
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - gersemi-network

  api:
    build:
      context: .
      dockerfile: Presentation/Dockerfile
    image: "${DOCKERHUB_USERNAME}/gersemi-api:${DOCKER_TAG}"
    ports:
      - "7098:7098"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Database=GersemiDb;Username=postgres;Password=${DB_PASSWORD};Port=5432
    depends_on:
      - db
    networks:
      - gersemi-network

  client:
    build:
      context: ../GERSEMI.Client
      dockerfile: Dockerfile
    image: "${DOCKERHUB_USERNAME}/gersemi-client:${DOCKER_TAG}"
    ports:
      - "4200:4200"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=development
      - NPM_CONFIG_OPTIONAL=true
    depends_on:
      - api
    networks:
      - gersemi-network
    volumes:
      - ../GERSEMI.Client:/app
      - client_node_modules:/app/node_modules  

volumes:
  postgres-data:
  client_node_modules:  

networks:
  gersemi-network:
    driver: bridge
