name: CI/CD Pipeline - Dev

on:
  push:
    branches:
      - dev

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 60  
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Install dependencies
        run: dotnet restore GERSEMI/GERSEMI.sln  

      - name: Build
        run: dotnet build GERSEMI/GERSEMI.sln --no-restore --configuration Release  

      - name: Run tests
        run: dotnet test GERSEMI/GERSEMI.sln --no-build --configuration Release --collect:"XPlat Code Coverage"  

      - name: Publish Test Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: TestResults
          path: '**/TestResults/*.trx'

  build-and-push-docker-images:
    runs-on: ubuntu-latest
    needs: build-and-test
    timeout-minutes: 60  
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push API image for dev branch
        uses: docker/build-push-action@v3
        with:
          context: .
          file: GERSEMI/Presentation/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/gersemi-api:dev
          platforms: linux/arm64

      - name: Build and push Client image for dev branch
        uses: docker/build-push-action@v3
        with:
          context: ./GERSEMI.Client
          file: GERSEMI.Client/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/gersemi-client:dev
          platforms: linux/arm64

  deploy-dev:
    runs-on: ubuntu-latest
    needs: build-and-push-docker-images
    if: github.ref == 'refs/heads/dev'
    timeout-minutes: 120  
    env:
      DEPLOY_BRANCH: 'dev'
      DOCKER_TAG: 'dev'
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      SA_PASSWORD: ${{ secrets.SA_PASSWORD }}
      RASPBERRY_HOST_IP: ${{ secrets.RASPBERRY_HOST_IP }}
      RASPBERRY_USERNAME: ${{ secrets.RASPBERRY_USERNAME }}
      RASPBERRY_SSH_KEY: ${{ secrets.RASPBERRY_SSH_KEY }}
      RASPBERRY_HOST_PORT: ${{ secrets.RASPBERRY_HOST_PORT }}

    steps:
      - name: Deploy to Raspberry Pi (Dev)
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ env.RASPBERRY_HOST_IP }}
          username: ${{ env.RASPBERRY_USERNAME }}
          key: ${{ env.RASPBERRY_SSH_KEY }}
          port: ${{ env.RASPBERRY_HOST_PORT }}
          script: |
            echo "Starting deployment for branch: $DEPLOY_BRANCH"
            echo "DOCKER_TAG set to: $DOCKER_TAG"
            echo "DOCKERHUB_USERNAME set to: $DOCKERHUB_USERNAME"
            echo "SA_PASSWORD is set."

            set -e
            cd ~/GERSEMI

            # Clean repository to avoid conflicts
            git reset --hard HEAD
            git clean -fd

            # Checkout the deployment branch
            git checkout $DEPLOY_BRANCH || { echo "Failed to checkout branch $DEPLOY_BRANCH"; exit 1; }

            # Pull the latest changes for the deployment branch
            git fetch origin $DEPLOY_BRANCH
            git merge --ff-only origin/$DEPLOY_BRANCH || {
              echo "Fast-forward failed. Resetting branch to origin/$DEPLOY_BRANCH"
              git reset --hard origin/$DEPLOY_BRANCH
            }

            # Debugging: Check git status and latest commit after pull
            echo "After pull:"
            git status
            git log -1

            # Export environment variables for Docker Compose
            export DOCKERHUB_USERNAME=$DOCKERHUB_USERNAME
            export DOCKER_TAG=$DOCKER_TAG

            # Navigate to Docker Compose directory
            cd ~/GERSEMI/GERSEMI

            # Stop and remove existing containers to prevent name conflicts
            docker-compose down --remove-orphans

            # Pull the latest Docker images
            docker-compose pull

            # Rebuild and restart Docker containers
            docker-compose up -d --build

            # Optionally, switch back to the main branch to maintain its state
            git checkout main
        timeout: 1800  
